services:
  backend:
    build: ./backend
    container_name: movie-app-backend
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    container_name: movie-app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend